---
title: "README"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    keep_md: true
---

# Overview
Visualise the results of F test to compare two variances, Student's t-test, test of equal or given proportions, Pearson's chi-squared test for count data and test for association/correlation between paired samples.

# Installation

```{r eval=FALSE, include=TRUE}
# CRAN installation:
install.packages("gginference")

# Or the development version from GitHub:
# install.packages("devtools")
devtools::install_github("okgreece/gginference")
```

# Usage

## One sample

### One sample z-test with Normal population or $n \ge 30$ and σ^2 known or unknown

The following table shows the rejection region which is calculated in \pkg{gginference} and the parameters of ```t.test```.

+-------------+----------------+--------------------------------------+---------------------------------------------------------+
| $H_0$       | $H_1$          | Rejection Region of **_gginference_**| Parameters of ```t.test()```                            |
+=============+================+======================================+=========================================================+
|$\mu = \mu_0$|$\mu < \mu_0$   |$R= \{z<-z_{a} \}$                    | - _x_ = vector of sample data,                          |
|             |                |                                      | - _mu_ = $\mu_0$,                                       |
|             |                |                                      | - _alternative_ = "less"                                |
+-------------+----------------+--------------------------------------+---------------------------------------------------------+
|             |$\mu > \mu_0$   |$R= \{z>z_{a}\}$                      | - _x_ = vector of sample data,                          |
|             |                |                                      | - _mu_ = $\mu_0$,                                       |
|             |                |                                      | - _alternative_ = "greater"                             |
+-------------+----------------+--------------------------------------+---------------------------------------------------------+
|             |$\mu \neq \mu_0$|$R= \{ |z|>z_{a/2} \}$                | - _x_ = vector of sample data,                          |
|             |                |                                      | - _mu_ = $\mu_0$,                                       |
|             |                |                                      | - _alternative_ = "two.sided"                           |
+-------------+----------------+--------------------------------------+---------------------------------------------------------+

where $z=\frac{\overline{X}-\mu_0}{\frac{\sigma}{\sqrt{n}}}$

where $z=\frac{\overline{X}-\mu_0}{s/\sqrt{n}}$

### One sample t-test with Normal population and $n < 30$ and σ^2 unknown

+-------------+----------------+--------------------------------------+---------------------------------------------------------+
| $H_0$       | $H_1$          | Rejection Region of **_gginference_**| Parameters of ```t.test()```                            |
+=============+================+======================================+=========================================================+
|$\mu = \mu_0$|$\mu < \mu_0$   | $R=\{t<-t_{n-1,a}\}$                 | - _x_ = vector of sample data,                          |
|             |                |                                      | - _mu_ = $\mu_0$,                                       |
|             |                |                                      | - _alternative_ = "less"                                |
+-------------+----------------+--------------------------------------+---------------------------------------------------------+
|             |$\mu > \mu_0$   | $R=\{t>t_{n-1,a}\}$                  | - _x_ = vector of sample data,                          |
|             |                |                                      | - _mu_ = $\mu_0$,                                       |
|             |                |                                      | - _alternative_ = "greater"                             |
+-------------+----------------+--------------------------------------+---------------------------------------------------------+
|             |$\mu \neq \mu_0$| $R=\{|t|>t_{n-1,a/2}\}$              | - _x_ = vector of sample data,                          |
|             |                |                                      | - _mu_ = $\mu_0$,                                       |
|             |                |                                      | - _alternative_ = "two.sided"                           |
+-------------+----------------+--------------------------------------+---------------------------------------------------------+

where $t=\frac{\overline{X}-\mu_0}{s/\sqrt{n}}$ 

## Two samples

### Two independent samples z-test with Normal population, $n_1,n_2>30$ and $\sigma_1^2$ and $\sigma_2^2$ are known or unknown

+----------------------+------------------------+--------------------------------------+---------------------------------------------------------+
| $H_0$                | $H_1$                  | Rejection Region of **_gginference_**| Parameters of ```t.test()```                            |
+======================+========================+======================================+=========================================================+
|$\mu_1 - \mu_2 = d_0$ | $\mu_1-\mu_2 < d_0$    | $R=\{z<-z_{a}\}$                     | - _x_ = vector of sample 1 data,                        |
|                      |                        |                                      | - _y_ = vector of sample 2 data,                        |
|                      |                        |                                      | - _paired_ = FALSE,                                     |
|                      |                        |                                      | - _var.equal_ = FALSE,                                  |
|                      |                        |                                      | - _alternative_ = "less"                                |
+----------------------+------------------------+--------------------------------------+---------------------------------------------------------+
|                      | $\mu_1-\mu_2 > d_0$    | $R=\{z>z_{a}\}$                      | - _x_ = vector of sample 1 data,                        |
|                      |                        |                                      | - _y_ = vector of sample 2 data,                        |
|                      |                        |                                      | - _paired_ = FALSE,                                     |
|                      |                        |                                      | - _var.equal_ = FALSE,                                  |
|                      |                        |                                      | - _alternative_ = "greater"                             |
+----------------------+------------------------+--------------------------------------+---------------------------------------------------------+
|                      | $\mu_1-\mu_2 \neq d_0$ | $R= \{|z|>z_{a/2} \}$                | - _x_ = vector of sample 1 data,                        |
|                      |                        |                                      | - _y_ = vector of sample 2 data,                        |
|                      |                        |                                      | - _paired_ = FALSE,                                     |
|                      |                        |                                      | - _var.equal_ = FALSE,                                  |
|                      |                        |                                      | - _alternative_ = "two.sided"                           |
+----------------------+------------------------+--------------------------------------+---------------------------------------------------------+

where $z=\frac{\overline{x_1}-\overline{x_2}-d_0}{ \sqrt{\frac{\sigma_{1}^2}{n_1} + \frac{\sigma_2^2}{n_2}}}$

where $z=\frac{\overline{x_1}-\overline{x_2}-d_0}{ \sqrt{\frac{s_{1}^2}{n_1} + \frac{s_2^2}{n_2}}}$




### Two independent samples t-test with Normal population $n_1, n_2 < 30$ and $\sigma_1^2 = \sigma_2^2 = \sigma^2$

+----------------------+------------------------+--------------------------------------+---------------------------------------------------------+
| $H_0$                | $H_1$                  | Rejection Region of **_gginference_**| Parameters of ```t.test()```                            |
+======================+========================+======================================+=========================================================+
|$\mu_1 - \mu_2 = d_0$ | $\mu_1-\mu_2 < d_0$    | $R=\{t<-t_{n_1+n_2-2,a}\}$           | - _x_ = vector of sample 1 data,                        |
|                      |                        |                                      | - _y_ = vector of sample 2 data,                        |
|                      |                        |                                      | - _paired_ = FALSE,                                     |
|                      |                        |                                      | - _var.equal_ = TRUE,                                   |
|                      |                        |                                      | - _alternative_ = "less"                                |
+----------------------+------------------------+--------------------------------------+---------------------------------------------------------+
|                      | $\mu_1-\mu_2 > d_0$    | $R=\{t>t_{n_1+n_2-2,a}\}$            | - _x_ = vector of sample 1 data,                        |
|                      |                        |                                      | - _y_ = vector of sample 2 data,                        |
|                      |                        |                                      | - _paired_ = FALSE,                                     |
|                      |                        |                                      | - _var.equal_ = TRUE,                                   |
|                      |                        |                                      | - _alternative_ = "greater"                             |
+----------------------+------------------------+--------------------------------------+---------------------------------------------------------+
|                      | $\mu_1-\mu_2 \neq d_0$ | $R= \{|t|>t_{n_1+n_2-2,a/2} \}$      | - _x_ = vector of sample 1 data,                        |
|                      |                        |                                      | - _y_ = vector of sample 2 data,                        |
|                      |                        |                                      | - _paired_ = FALSE,                                     |
|                      |                        |                                      | - _var.equal_ = TRUE,                                   |
|                      |                        |                                      | - _alternative_ = "two.sided"                           |
+----------------------+------------------------+--------------------------------------+---------------------------------------------------------+

where $t=\frac{\overline{x_1}-\overline{x_2}-d_0}{ \sqrt{\frac{(n_1-1) s_{1}^2+(n_2-1)s_{2}^2}{n_{1}+n_{2}-2}}\sqrt{\frac{1}{n_1}+\frac{1}{n_2}}}$


### Two independent samples t-test with Normal population $n_1, n_2 < 30$ equal or unequal sizes and $\sigma_1^2 \neq \sigma_2^2$

+----------------------+------------------------+--------------------------------------+---------------------------------------------------------+
| $H_0$                | $H_1$                  | Rejection Region of **_gginference_**| Parameters of ```t.test()```                            |
+======================+========================+======================================+=========================================================+
|$\mu_1 - \mu_2 = d_0$ | $\mu_1-\mu_2 < d_0$    | $R=\{t<-t_{\nu,a}\}$                 | - _x_ = vector of sample 1 data,                        |
|                      |                        |                                      | - _y_ = vector of sample 2 data,                        |
|                      |                        |                                      | - _paired_ = FALSE,                                     |
|                      |                        |                                      | - _var.equal_ = FALSE,                                  |
|                      |                        |                                      | - _alternative_ = "less"                                |
+----------------------+------------------------+--------------------------------------+---------------------------------------------------------+
|                      | $\mu_1-\mu_2 > d_0$    | $R=\{t>t_{\nu,a}\}$                  | - _x_ = vector of sample 1 data,                        |
|                      |                        |                                      | - _y_ = vector of sample 2 data,                        |
|                      |                        |                                      | - _paired_ = FALSE,                                     |
|                      |                        |                                      | - _var.equal_ = FALSE,                                  |
|                      |                        |                                      | - _alternative_ = "greater"                             |
+----------------------+------------------------+--------------------------------------+---------------------------------------------------------+
|                      | $\mu_1-\mu_2 \neq d_0$ | $R= \{|t|>t_{\nu,a/2} \}$            | - _x_ = vector of sample 1 data,                        |
|                      |                        |                                      | - _y_ = vector of sample 2 data,                        |
|                      |                        |                                      | - _paired_ = FALSE,                                     |
|                      |                        |                                      | - _var.equal_ = FALSE,                                  |
|                      |                        |                                      | - _alternative_ = "two.sided"                           |
+----------------------+------------------------+--------------------------------------+---------------------------------------------------------+

where $t=\frac{\overline{x_1}-\overline{x_2}-d_0}{ \sqrt{\frac{s_{1}^2}{n_1} + \frac{s_2^2}{n_2}}}$

$\nu$ degrees of freedom, if 

- $n_1=n_2$, $\nu=2(n-1)$
- $n_1 \neq n_2$, $\nu = \frac{(\frac{s_1^2}{n_1}+\frac{s_2^2}{n_2})^2}{\frac{(\frac{s_1^2}{n_1})^2}{n_1-1}+\frac{(\frac{s_2^2}{n_2})^2}{n_2-2}})$



## Paired samples with Normal population $n \le 30$

+--------------------+------------------------+--------------------------------------+---------------------------------------------------------+
| $H_0$              | $H_1$                  | Rejection Region of **_gginference_**| Parameters of ```t.test()```                            |
+====================+========================+======================================+=========================================================+
|$\mu_1-\mu_2 = d_0$ | $\mu_1-\mu_2 < d_0$    | $R=\{t<-t_{n-1,a}\}$                 | - _x_ = vector of sample 1 data,                        |
|                    |                        |                                      | - _y_ = vector of sample 2 data,                        |
|                    |                        |                                      | - _paired_ = FALSE,                                     |
|                    |                        |                                      | - _var.equal_ = FALSE,                                  |
|                    |                        |                                      | - _alternative_ = "less"                                |
+--------------------+------------------------+--------------------------------------+---------------------------------------------------------+
|                    | $\mu_1-\mu_2 > d_0$    | $R=\{t>t_{n-1,a}\}$                  | - _x_ = vector of sample 1 data,                        |
|                    |                        |                                      | - _y_ = vector of sample 2 data,                        |
|                    |                        |                                      | - _paired_ = FALSE,                                     |
|                    |                        |                                      | - _var.equal_ = FALSE,                                  |
|                    |                        |                                      | - _alternative_ = "greater"                             |
+--------------------+------------------------+--------------------------------------+---------------------------------------------------------+
|                    | $\mu_1-\mu_2 \neq d_0$ | $R= \{|t|>t_{n-1,a/2} \}$            | - _x_ = vector of sample 1 data,                        |
|                    |                        |                                      | - _y_ = vector of sample 2 data,                        |
|                    |                        |                                      | - _paired_ = FALSE,                                     |
|                    |                        |                                      | - _var.equal_ = FALSE,                                  |
|                    |                        |                                      | - _alternative_ = "two.sided"                           |
+--------------------+------------------------+--------------------------------------+---------------------------------------------------------+

where $t=\frac{\overline{d}-d_0}{ s_d/\sqrt{n}}$

$\overline{d}=\frac{1}{n} \sum_{i=1}^{n}(x_{1_i}-x_{2_i})=\frac{1}{n} \sum_{i=1}^{n}d_i$

$s_d^2= \frac{1}{n-1} \sum_{i=1}^n(d_i- \overline{d})^2$



## Proportion test

### One-proportion z-test


+-------------+----------------+--------------------------------------+---------------------------------------------------------+
| $H_0$       | $H_1$          | Rejection Region of **_gginference_**| Parameters of ```ggproptest()```                        |
+=============+================+======================================+=========================================================+
|$p = p_0$    | $p < p_0$      | $R= \{z<-z_{a} \}$                   | - _x_ = vector of sample data,                          |
|             |                |                                      | - _mu_ = $\mu_0$,                                       |
|             |                |                                      | - _alternative_ = "less"                                |
+-------------+----------------+--------------------------------------+---------------------------------------------------------+
|             | $p > p_0$      | $R= \{z>z_{a}\}$                     | - _x_ = vector of sample data,                          |
|             |                |                                      | - _mu_ = $\mu_0$,                                       |
|             |                |                                      | - _alternative_ = "greater"                             |
+-------------+----------------+--------------------------------------+---------------------------------------------------------+
|             | $p \neq p_0$   | $R= \{|z|>z_{a/2} \}$                | - _x_ = vector of sample data,                          |
|             |                |                                      | - _mu_ = $\mu_0$,                                       |
|             |                |                                      | - _alternative_ = "two.sided"                           |
+-------------+----------------+--------------------------------------+---------------------------------------------------------+

where $z=\frac{\hat{p}-p_0}{\sqrt{p_0(1-p_0)}}\sqrt{n}$

$\hat{p}=\frac{x}{n}$


### Two-proportion z-test



+-------------------+-----------------------+--------------------------------------+---------------------------------------------------------+
| $H_0$             | $H_1$                 | Rejection Region of **_gginference_**| Parameters of ```ggproptest()```                        |
+===================+=======================+======================================+=========================================================+
| $p_1 - p_2 = d_0$ | $p_1-p_2 < d_0$       | $R=\{z<-z_{a}\}$                     | - _x_ = vector of sample 1 data,                        |
|                   |                       |                                      | - _y_ = vector of sample 2 data,                        |
|                   |                       |                                      | - _paired_ = FALSE,                                     |
|                   |                       |                                      | - _var.equal_ = FALSE,                                  |
|                   |                       |                                      | - _alternative_ = "less"                                |
+-------------------+-----------------------+--------------------------------------+---------------------------------------------------------+
|                   | $p_1-p_2 > d_0$       | $R=\{z>z_{a}\}$                      | - _x_ = vector of sample 1 data,                        |
|                   |                       |                                      | - _y_ = vector of sample 2 data,                        |
|                   |                       |                                      | - _paired_ = FALSE,                                     |
|                   |                       |                                      | - _var.equal_ = FALSE,                                  |
|                   |                       |                                      | - _alternative_ = "greater"                             |
+-------------------+-----------------------+--------------------------------------+---------------------------------------------------------+
|                   | $p_1-p_2 \neq d_0$    | $R= \{|z|>z_{a/2} \}$                | - _x_ = vector of sample 1 data,                        |
|                   |                       |                                      | - _y_ = vector of sample 2 data,                        |
|                   |                       |                                      | - _paired_ = FALSE,                                     |
|                   |                       |                                      | - _var.equal_ = FALSE,                                  |
|                   |                       |                                      | - _alternative_ = "two.sided"                           |
+-------------------+-----------------------+--------------------------------------+---------------------------------------------------------+

where $z=\frac{\hat{p_1}-\hat{p_2}-d_0}{s}$

if $d_0 = 0$, $s \approx \sqrt{\hat{p}(1-\hat{p}) (\frac{1}{n_1}+\frac{1}{n_2})}$

if $d_0 \neq 0$, $s = \sqrt{\frac{\hat{p}_1(1-\hat{p}_1)}{n_1} +\frac{\hat{p}_2(1-\hat{p}_2)}{n_2}} $

$\hat{p_1} = \frac{x_1}{n_1}$
$\hat{p_2} = \frac{x_1}{n_2}$
$\hat{p} = \frac{x_1+x_2}{n_1+n_2}$


## Two-sample F test for equality of variances

+-------------------------------------+----------------------------------------+--------------------------------------+---------------------------------------------------------+
| $H_0$                               | $H_1$                                  | Rejection Region of **_gginference_**| Parameters of ```ggvartest()```                         |
+=====================================+========================================+======================================+=========================================================+
| $\frac{\sigma_1^2}{\sigma_2^2} = 1$ | $\frac{\sigma_1^2}{\sigma_2^2} < 1$    | $R= \{F>F_{n_1-1,n_2-1,1-a}\}$       | - _x_ = vector of sample 1 data,                        |
|                                     |                                        |                                      | - _y_ = vector of sample 2 data,                        |
|                                     |                                        |                                      | - _ratio_ = 1                                           |
|                                     |                                        |                                      | - _alternative_ = "less"                                |
+-------------------------------------+----------------------------------------+--------------------------------------+---------------------------------------------------------+
|                                     | $\frac{\sigma_1^2}{\sigma_2^2} > 1$    | $R= \{F>F_{n_1-1,n_2-1,a}\}$         | - _x_ = vector of sample data,                          |
|                                     |                                        |                                      | - _mu_ = $\mu_0$,                                       |
|                                     |                                        |                                      | - _ratio_ = 1                                           |
|                                     |                                        |                                      | - _alternative_ = "greater"                             |
+-------------------------------------+----------------------------------------+--------------------------------------+---------------------------------------------------------+
|                                     | $\frac{\sigma_1^2}{\sigma_2^2} \neq 1$ | $R= \{F>F_{n_1-1,n_2-1,a/2}\}$       | - _x_ = vector of sample data,                          |
|                                     |                                        |                                      | - _mu_ = $\mu_0$,                                       |
|                                     |                                        |                                      | - _ratio_ = 1                                           |
|                                     |                                        |                                      | - _alternative_ = "two.sided"                           |
+-------------------------------------+----------------------------------------+--------------------------------------+---------------------------------------------------------+

where $F=\frac{s_1^2}{s_2^2}, s_1^2>s_2^2$



## ```ggcortest()```

Test                             | $H_0$             | $H_1$              | Rejection Region                 | Definition
---------------------------------| ------------------| -------------------| ---------------------------------|-------------
Correlation test                 | $\varrho = 0$   | $\varrho \neq 0$ | $R= \{|t|>t_{n-2,a/2} \}$   | $t=\frac{r\sqrt{n-2}}{\sqrt{1-r^2}}$






## Chi-squared Test of Independence


+-------------------------+---------------------------------------+--------------------------------------+---------------------------------------------------------+
| $H_0$                   | $H_1$                                 | Rejection Region of **_gginference_**| Parameters of ```ggchisqtest()```                       |
+=========================+=======================================+======================================+=========================================================+
|    Two variables        |        Two variables                  | $R= \{ X^2> \chi_{a/2}^2 \}$         | - _x_ = 2-dimensional contingency table                 |
|   are independent       |     are not independent               |                                      |                                                         |
+-------------------------+---------------------------------------+--------------------------------------+---------------------------------------------------------+

where $\chi^2= \sum_{n=1}^{n}\frac{(O_i-E_i)^2}{Ei}$


## ANOVA F-test


+-------------------------+---------------------------+--------------------------------------+-------------------------------------------------------------------+
| $H_0$                   | $H_1$                     | Rejection Region of **_gginference_**| Parameters of ```ggaov()```                                       |
+=========================+===========================+======================================+===================================================================+
| $H_0: \mu_1 = \mu_2 = $ |  Not all three population | $R= \{ F>F_k-1,n-k,a \}$             | - _formula_ = 2-dimensional contingency table                     |
|      $...=\mu_k$        |     means are equal       |                                      | - _data_ = data frame with the variables specified in the formula |
+-------------------------+---------------------------+--------------------------------------+-------------------------------------------------------------------+

where $F=\frac{\sum_{i=1}^kn_i(\overline{Y}_i-\overline{Y})^2/(k-1)}{\sum_{i=1}^k\sum_{j=1}^{n_i}(Y_{ij}-\overline{Y}_i)^2/(n-k)}$ 
  

# Getting help

If you encounter a bug, please feel free to open an [issue](https://github.com/okgreece/gginference/issues) with a minimal reproducible example.


